package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"transformer/internal/aws"
)

// Generator represents an OpenTofu configuration generator
type Generator struct {
	outputDir string
	verbose   bool
	fixes     *OpenTofuFixes
}

// NewGenerator creates a new generator instance
func NewGenerator(outputDir string, verbose bool) *Generator {
	return &Generator{
		outputDir: outputDir,
		verbose:   verbose,
		fixes:     NewOpenTofuFixes(),
	}
}

// Generate creates OpenTofu configuration files from AWS resources
func (g *Generator) Generate(resources []aws.Resource, region string, generateStateFile bool) error {
	// Create output directory
	if err := os.MkdirAll(g.outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Group resources by type
	resourceGroups := g.groupResourcesByType(resources)

	// Generate main configuration file
	if err := g.generateMain(resourceGroups, region); err != nil {
		return fmt.Errorf("failed to generate main.tf: %w", err)
	}

	// Generate variables file
	if err := g.generateVariables(resources); err != nil {
		return fmt.Errorf("failed to generate variables.tf: %w", err)
	}

	// Generate outputs file
	if err := g.generateOutputs(resourceGroups); err != nil {
		return fmt.Errorf("failed to generate outputs.tf: %w", err)
	}

	// Generate versions file
	if err := g.generateVersions(); err != nil {
		return fmt.Errorf("failed to generate versions.tf: %w", err)
	}

	// Generate state file (Terraformer-like functionality) if requested
	if generateStateFile {
		if err := g.generateStateFile(resourceGroups, region); err != nil {
			return fmt.Errorf("failed to generate terraform.tfstate: %w", err)
		}
	}

	// Generate README file
	if err := g.generateREADME(resources, region, generateStateFile); err != nil {
		return fmt.Errorf("failed to generate README.md: %w", err)
	}

	// Generate modules for each resource type
	for resourceType, resourceList := range resourceGroups {
		if len(resourceList) > 0 {
			if err := g.generateModule(resourceType, resourceList); err != nil {
				if g.verbose {
					fmt.Printf("Warning: Failed to generate module for %s: %v\n", resourceType, err)
				}
			}
		}
	}

	return nil
}

// groupResourcesByType groups resources by their type
func (g *Generator) groupResourcesByType(resources []aws.Resource) map[string][]aws.Resource {
	groups := make(map[string][]aws.Resource)
	for _, resource := range resources {
		resourceType := resource.GetType()
		groups[resourceType] = append(groups[resourceType], resource)
	}
	return groups
}

// generateMain generates the main.tf file
func (g *Generator) generateMain(resourceGroups map[string][]aws.Resource, region string) error {
	content := fmt.Sprintf(`# AWS to OpenTofu Infrastructure Configuration
# Generated by AWS Transformer
# Region: %s

# Configure the AWS Provider
provider "aws" {
  region = "%s"
  
  default_tags {
    tags = {
      Environment = "production"
      ManagedBy   = "opentofu"
      Project     = "aws-transformer"
    }
  }
}

# Global variables are defined in variables.tf

# Data sources
data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

# Module calls
`, region, region)

	// Add module calls for each resource type
	resourceTypes := make([]string, 0, len(resourceGroups))
	for resourceType := range resourceGroups {
		resourceTypes = append(resourceTypes, resourceType)
	}
	sort.Strings(resourceTypes)

	for _, resourceType := range resourceTypes {
		resources := resourceGroups[resourceType]
		if len(resources) > 0 {
			moduleName := strings.ToLower(resourceType)
			
			// Add special handling for RDS module
			if resourceType == "rds" {
				content += fmt.Sprintf(`
module "%s" {
  source = "./modules/%s"
  
  # RDS password variables
  rds_password_aiml_dev_1e = var.rds_password_aiml_dev_1e
  rds_password_postgres_dev_onengine = var.rds_password_postgres_dev_onengine
  rds_password_retool = var.rds_password_retool
  rds_password_strapi_db_instance = var.rds_password_strapi_db_instance
  
  # Add module-specific variables here
  # Example:
  # vpc_id = module.vpc.vpc_id
}
`, moduleName, moduleName)
			} else {
				content += fmt.Sprintf(`
module "%s" {
  source = "./modules/%s"
  
  # Add module-specific variables here
  # Example:
  # vpc_id = module.vpc.vpc_id
}
`, moduleName, moduleName)
			}
		}
	}

	// Outputs are defined in outputs.tf
	content += `
`

	// Add module outputs
	for _, resourceType := range resourceTypes {
		resources := resourceGroups[resourceType]
		if len(resources) > 0 {
			moduleName := strings.ToLower(resourceType)
			content += fmt.Sprintf(`
output "%s_outputs" {
  description = "Outputs from %s module"
  value       = module.%s
}
`, moduleName, resourceType, moduleName)
		}
	}

	return g.writeFile(filepath.Join(g.outputDir, "main.tf"), content)
}

// generateVariables generates the variables.tf file
func (g *Generator) generateVariables(resources []aws.Resource) error {
	content := `# Variables for AWS to OpenTofu Infrastructure
# Generated by AWS Transformer

# Global variables
variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "aws_account_id" {
  description = "AWS account ID"
  type        = string
  default     = "YOUR_ACCOUNT_ID"
}

# Resource-specific variables
`

	// Group resources by type for variable generation
	resourceGroups := g.groupResourcesByType(resources)

	// Generate variables for each resource type
	resourceTypes := make([]string, 0, len(resourceGroups))
	for resourceType := range resourceGroups {
		resourceTypes = append(resourceTypes, resourceType)
	}
	sort.Strings(resourceTypes)

	for _, resourceType := range resourceTypes {
		resources := resourceGroups[resourceType]
		if len(resources) > 0 {
			switch resourceType {
			case "vpc":
				content += `variable "vpc_instances" {
  description = "VPC instance configurations"
  type = list(object({
    name = string
    cidr_block = string
    enable_dns_hostnames = bool
    enable_dns_support = bool
    instance_tenancy = string
    tags = map(string)
  }))
  default = []
}

`
			case "ec2":
				content += `variable "ec2_instances" {
  description = "EC2 instance configurations"
  type = list(object({
    name = string
    instance_type = string
    ami = string
    subnet_id = string
    security_groups = list(string)
    key_name = string
    iam_instance_profile = string
    user_data = string
    tags = map(string)
  }))
  default = []
}

`
			case "iam":
				content += `variable "iam_roles" {
  description = "IAM role configurations"
  type = list(object({
    name = string
    assume_role_policy = string
    managed_policy_arns = list(string)
    inline_policies = map(string)
    path = string
    description = string
    tags = map(string)
  }))
  default = []
}

`
			case "rds":
				content += `variable "rds_instances" {
  description = "RDS instance configurations"
  type = list(object({
    name = string
    engine = string
    engine_version = string
    instance_class = string
    allocated_storage = number
    storage_type = string
    storage_encrypted = bool
    db_name = string
    username = string
    password = string
    vpc_security_group_ids = list(string)
    db_subnet_group_name = string
    tags = map(string)
  }))
  default = []
}

`

				// Add individual password variables for each RDS instance
				for _, resource := range resources {
					resourceName := strings.ReplaceAll(resource.GetName(), "-", "_")
					resourceName = strings.ReplaceAll(resourceName, " ", "_")
					content += fmt.Sprintf(`variable "rds_password_%s" {
  description = "Password for RDS instance %s"
  type        = string
  sensitive   = true
  default     = "CHANGE_ME"
}

`, resourceName, resource.GetName())
				}

			case "s3":
				content += `variable "s3_buckets" {
  description = "S3 bucket configurations"
  type = list(object({
    name = string
    versioning_enabled = bool
    encryption_enabled = bool
    kms_key_id = string
    tags = map(string)
  }))
  default = []
}

`
			case "alb", "elb":
				content += `variable "load_balancers" {
  description = "Load balancer configurations"
  type = list(object({
    name = string
    internal = bool
    load_balancer_type = string
    security_groups = list(string)
    subnets = list(string)
    enable_deletion_protection = bool
    idle_timeout = number
    tags = map(string)
  }))
  default = []
}

`
			case "lambda":
				content += `variable "lambda_functions" {
  description = "Lambda function configurations"
  type = list(object({
    name = string
    runtime = string
    handler = string
    role = string
    code = string
    timeout = number
    memory_size = number
    environment = map(string)
    tags = map(string)
  }))
  default = []
}

`
			default:
				content += fmt.Sprintf(`variable "%s_resources" {
  description = "%s resource configurations"
  type = list(object({
    name = string
    attributes = map(string)
    tags = map(string)
  }))
  default = []
}

`, resourceType, strings.ToUpper(resourceType))
			}
		}
	}

	return g.writeFile(filepath.Join(g.outputDir, "variables.tf"), content)
}

// generateOutputs generates the outputs.tf file
func (g *Generator) generateOutputs(resourceGroups map[string][]aws.Resource) error {
	content := `# Outputs for AWS to OpenTofu Infrastructure
# Generated by AWS Transformer

# Global outputs
output "region" {
  description = "AWS region"
  value       = data.aws_region.current.name
}

output "account_id" {
  description = "AWS account ID"
  value       = data.aws_caller_identity.current.account_id
}

# Resource-specific outputs
`

	// Generate outputs for each resource type
	resourceTypes := make([]string, 0, len(resourceGroups))
	for resourceType := range resourceGroups {
		resourceTypes = append(resourceTypes, resourceType)
	}
	sort.Strings(resourceTypes)

	for _, resourceType := range resourceTypes {
		resources := resourceGroups[resourceType]
		if len(resources) > 0 {
			content += fmt.Sprintf(`# %s outputs
output "%s_resources" {
  description = "List of %s resources"
  value = module.%s
}

`, strings.ToUpper(resourceType), resourceType, resourceType, strings.ToLower(resourceType))
		}
	}

	return g.writeFile(filepath.Join(g.outputDir, "outputs.tf"), content)
}

// generateVersions generates the versions.tf file
func (g *Generator) generateVersions() error {
	content := `# Version constraints for AWS to OpenTofu Infrastructure
# Generated by AWS Transformer

terraform {
  required_version = ">= 1.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
`

	return g.writeFile(filepath.Join(g.outputDir, "versions.tf"), content)
}

// generateREADME generates the README.md file
func (g *Generator) generateREADME(resources []aws.Resource, region string, generateStateFile bool) error {
	content := fmt.Sprintf(`# AWS to OpenTofu Infrastructure Configuration

This directory contains OpenTofu (formerly Terraform) configuration files generated from your existing AWS infrastructure.

## Overview

- **Generated by**: AWS Transformer CLI
- **Region**: %s
- **Total Resources**: %d
- **Resource Types**: %d

## File Structure

- **main.tf** - Main OpenTofu configuration with provider setup and module calls
- **variables.tf** - Variable definitions for all resources
- **outputs.tf** - Output definitions
- **versions.tf** - Provider version constraints
`, region, len(resources), len(g.groupResourcesByType(resources)))

	if generateStateFile {
		content += `- **terraform.tfstate** - Complete state file with all discovered resources (Terraformer-like)
`
	}

	content += `- **README.md** - This documentation file
- **modules/** - Resource-specific modules

## Resource Types

`

	// Add resource type summary
	resourceGroups := g.groupResourcesByType(resources)
	resourceTypes := make([]string, 0, len(resourceGroups))
	for resourceType := range resourceGroups {
		resourceTypes = append(resourceTypes, resourceType)
	}
	sort.Strings(resourceTypes)

	for _, resourceType := range resourceTypes {
		resources := resourceGroups[resourceType]
		content += fmt.Sprintf("- **%s**: %d resources\n", strings.ToUpper(resourceType), len(resources))
	}

	content += `
## Usage

### Prerequisites

1. Install OpenTofu (formerly Terraform)
2. Configure AWS credentials
3. Review and update sensitive values

### Quick Start

1. **Initialize OpenTofu**:
   Run: tofu init

2. **Review the plan**:
   Run: tofu plan

3. **Apply the configuration**:
   Run: tofu apply
`

	if generateStateFile {
		content += `
### Terraformer-like State File

This generation includes a complete terraform.tfstate file with all discovered resources, similar to Terraformer's approach. This means:

- **✅ Ready-to-use state**: The state file contains all your discovered AWS resources
- **✅ No manual import needed**: Resources are already in the state file
- **✅ Immediate validation**: Run tofu plan to verify everything is in sync
- **✅ Production ready**: The state file matches your actual AWS infrastructure

**Expected behavior**: After running tofu plan, you should see "No changes. Objects have not been modified." This confirms that your OpenTofu configuration matches your existing AWS infrastructure.
`
	}

	content += `
### Important Notes

⚠️ **Before applying this configuration:**

1. **Review all resources** - Ensure the generated configuration matches your expectations
2. **Update sensitive values** - Replace placeholder values for passwords, keys, etc.
3. **Test in non-production** - Always test in a safe environment first
4. **Backup existing infrastructure** - Create backups before making changes
5. **Check dependencies** - Ensure all required resources exist

### Customization

You can customize the generated configuration by:

1. **Modifying variables** - Update values in variables.tf
2. **Adding resources** - Extend the configuration with additional resources
3. **Adjusting modules** - Modify resource-specific modules in the modules/ directory
4. **Updating tags** - Modify default tags in main.tf

### Security Considerations

- Review and update all password variables
- Ensure proper IAM permissions
- Validate security group configurations
- Check encryption settings
- Review public access settings

### Troubleshooting

Common issues and solutions:

1. **Provider version conflicts** - Update versions.tf if needed
2. **Missing dependencies** - Ensure all referenced resources exist
3. **Permission errors** - Verify AWS credentials and permissions
4. **Resource conflicts** - Check for naming conflicts

## Support

For issues with the generated configuration:

1. Review the OpenTofu documentation
2. Check AWS service documentation
3. Validate your AWS credentials and permissions
4. Test with a subset of resources first

## Generated Configuration Details

This configuration was generated using the AWS Transformer CLI tool, which:

- Discovers existing AWS resources
- Generates corresponding OpenTofu configuration
- Creates modular, maintainable code
- Includes proper variable definitions
- Provides comprehensive documentation

The generated code follows OpenTofu best practices and includes:

- Proper resource naming and tagging
- Modular architecture
- Variable-based configuration
- Comprehensive outputs
- Security best practices
`

	return g.writeFile(filepath.Join(g.outputDir, "README.md"), content)
}

// generateModule generates a module for a specific resource type
func (g *Generator) generateModule(resourceType string, resources []aws.Resource) error {
	moduleDir := filepath.Join(g.outputDir, "modules", strings.ToLower(resourceType))
	
	// Create module directory
	if err := os.MkdirAll(moduleDir, 0755); err != nil {
		return fmt.Errorf("failed to create module directory: %w", err)
	}

	// Generate main.tf for the module
	if err := g.generateModuleMain(moduleDir, resourceType, resources); err != nil {
		return fmt.Errorf("failed to generate module main.tf: %w", err)
	}

	// Generate variables.tf for the module
	if err := g.generateModuleVariables(moduleDir, resourceType, resources); err != nil {
		return fmt.Errorf("failed to generate module variables.tf: %w", err)
	}

	// Generate outputs.tf for the module
	if err := g.generateModuleOutputs(moduleDir, resourceType, resources); err != nil {
		return fmt.Errorf("failed to generate module outputs.tf: %w", err)
	}

	return nil
}

// generateModuleMain generates the main.tf file for a module
func (g *Generator) generateModuleMain(moduleDir, resourceType string, resources []aws.Resource) error {
	content := fmt.Sprintf(`# %s module
# Generated by AWS Transformer

`, strings.ToUpper(resourceType))

	// Track seen resources to prevent duplicates
	seenResources := make(map[string]bool)
	uniqueResources := []aws.Resource{}

	// Filter out duplicates
	for _, resource := range resources {
		resourceID := resource.GetID()
		if !seenResources[resourceID] {
			seenResources[resourceID] = true
			uniqueResources = append(uniqueResources, resource)
		}
	}

	// Generate resource definitions
	for i, resource := range uniqueResources {
		tofuConfig, err := resource.ToOpenTofu()
		if err != nil {
			if g.verbose {
				fmt.Printf("Warning: Failed to generate OpenTofu config for resource %s: %v\n", resource.GetName(), err)
			}
			continue
		}

		// Apply OpenTofu compatibility fixes
		fixedConfig := g.fixes.ApplyAllFixes(resource.GetType(), tofuConfig)

		if i > 0 {
			content += "\n"
		}
		content += fixedConfig
	}

	return g.writeFile(filepath.Join(moduleDir, "main.tf"), content)
}

// generateModuleVariables generates the variables.tf file for a module
func (g *Generator) generateModuleVariables(moduleDir, resourceType string, resources []aws.Resource) error {
	content := fmt.Sprintf(`# Variables for %s module
# Generated by AWS Transformer

`, strings.ToUpper(resourceType))

	// Add module-specific variables based on resource type
	switch resourceType {
	case "vpc":
		content += `variable "vpc_instances" {
  description = "VPC instance configurations"
  type = list(object({
    name = string
    cidr_block = string
    enable_dns_hostnames = bool
    enable_dns_support = bool
    instance_tenancy = string
    tags = map(string)
  }))
  default = []
}
`
	case "ec2":
		content += `variable "ec2_instances" {
  description = "EC2 instance configurations"
  type = list(object({
    name = string
    instance_type = string
    ami = string
    subnet_id = string
    security_groups = list(string)
    key_name = string
    iam_instance_profile = string
    user_data = string
    tags = map(string)
  }))
  default = []
}
`
	case "iam":
		content += `variable "iam_roles" {
  description = "IAM role configurations"
  type = list(object({
    name = string
    assume_role_policy = string
    managed_policy_arns = list(string)
    inline_policies = map(string)
    path = string
    description = string
    tags = map(string)
  }))
  default = []
}
`
	case "rds":
		content += `variable "rds_instances" {
  description = "RDS instance configurations"
  type = list(object({
    name = string
    engine = string
    engine_version = string
    instance_class = string
    allocated_storage = number
    storage_type = string
    storage_encrypted = bool
    db_name = string
    username = string
    password = string
    vpc_security_group_ids = list(string)
    db_subnet_group_name = string
    tags = map(string)
  }))
  default = []
}
`
	default:
		content += fmt.Sprintf(`variable "%s_resources" {
  description = "%s resource configurations"
  type = list(object({
    name = string
    attributes = map(string)
    tags = map(string)
  }))
  default = []
}
`, resourceType, strings.ToUpper(resourceType))
	}

	// Apply fixes to add missing variables
	content = g.fixes.GenerateMissingVariables(content)
	
	return g.writeFile(filepath.Join(moduleDir, "variables.tf"), content)
}

// generateModuleOutputs generates the outputs.tf file for a module
func (g *Generator) generateModuleOutputs(moduleDir, resourceType string, resources []aws.Resource) error {
	content := fmt.Sprintf(`# Outputs for %s module
# Generated by AWS Transformer

`, strings.ToUpper(resourceType))

	// Add module-specific outputs based on resource type
	switch resourceType {
	case "vpc":
		content += `# VPC outputs - resources available as aws_vpc.*
`
	case "ec2":
		// Generate outputs based on actual EC2 instance names
		if len(resources) > 0 {
			content += `output "instance_ids" {
  description = "List of EC2 instance IDs"
  value       = [
`
			for i, resource := range resources {
				resourceName := g.sanitizeResourceName(resource.GetName())
				if i > 0 {
					content += ",\n"
				}
				content += fmt.Sprintf("    aws_instance.%s.id", resourceName)
			}
			content += `
  ]
}

output "instance_public_ips" {
  description = "List of EC2 instance public IPs"
  value       = [
`
			for i, resource := range resources {
				resourceName := g.sanitizeResourceName(resource.GetName())
				if i > 0 {
					content += ",\n"
				}
				content += fmt.Sprintf("    aws_instance.%s.public_ip", resourceName)
			}
			content += `
  ]
}
`
		} else {
			content += `# No EC2 instances found
`
		}
	case "iam":
		content += `# IAM role outputs - resources available as aws_iam_role.*
`
	case "rds":
		// Generate outputs based on actual RDS instance names
		if len(resources) > 0 {
			content += `output "db_instance_ids" {
  description = "List of RDS instance IDs"
  value       = [
`
			for i, resource := range resources {
				resourceName := g.sanitizeResourceName(resource.GetName())
				if i > 0 {
					content += ",\n"
				}
				content += fmt.Sprintf("    aws_db_instance.%s.id", resourceName)
			}
			content += `
  ]
}

output "db_endpoints" {
  description = "List of RDS instance endpoints"
  value       = [
`
			for i, resource := range resources {
				resourceName := g.sanitizeResourceName(resource.GetName())
				if i > 0 {
					content += ",\n"
				}
				content += fmt.Sprintf("    aws_db_instance.%s.endpoint", resourceName)
			}
			content += `
  ]
}
`
		} else {
			content += `# No RDS instances found
`
		}
	default:
		// Skip problematic output references for certain resource types
		if resourceType == "ec2" || resourceType == "rds" {
			content += fmt.Sprintf(`# %s outputs - resources available as aws_%s.*
# Note: Output references removed due to OpenTofu compatibility issues
`, strings.ToUpper(resourceType), resourceType)
		} else {
			content += fmt.Sprintf(`# %s outputs - resources available as aws_%s.*
`, strings.ToUpper(resourceType), resourceType)
		}
	}

	return g.writeFile(filepath.Join(moduleDir, "outputs.tf"), content)
}

// sanitizeResourceName converts a resource name to a valid OpenTofu resource name
func (g *Generator) sanitizeResourceName(name string) string {
	// Handle empty names
	if name == "" {
		return "resource"
	}
	
	// Replace invalid characters with underscores
	invalidChars := []string{"-", " ", ".", "/", "\\", ":", "*", "?", "\"", "<", ">", "|", "!", "@", "#", "$", "%", "^", "&", "(", ")", "+", "=", "[", "]", "{", "}", "|", "\\", ";", "'", ",", "?"}
	result := name
	
	for _, char := range invalidChars {
		result = strings.ReplaceAll(result, char, "_")
	}
	
	// Ensure it starts with a letter
	if len(result) > 0 && (result[0] < 'a' || result[0] > 'z') && (result[0] < 'A' || result[0] > 'Z') {
		result = "resource_" + result
	}
	
	// Limit length to 63 characters (OpenTofu resource name limit)
	if len(result) > 63 {
		// Keep the first 50 characters and last 13 characters to preserve uniqueness
		prefix := result[:50]
		suffix := result[len(result)-13:]
		result = prefix + "_" + suffix
	}
	
	// Remove any double underscores that might have been created
	result = strings.ReplaceAll(result, "__", "_")
	
	// Remove leading/trailing underscores
	result = strings.Trim(result, "_")
	
	// Ensure we have a valid name
	if result == "" {
		result = "resource"
	}
	
	return result
}

// writeFile writes content to a file
func (g *Generator) writeFile(filename string, content string) error {
	return os.WriteFile(filename, []byte(content), 0644)
} 

// generateStateFile generates a terraform.tfstate file with all discovered resources
func (g *Generator) generateStateFile(resourceGroups map[string][]aws.Resource, region string) error {
	content := `{
  "version": 4,
  "terraform_version": "1.0.0",
  "serial": 1,
  "lineage": "generated-by-aws-transformer",
  "outputs": {},
  "resources": [
`

	resourceTypes := make([]string, 0, len(resourceGroups))
	for resourceType := range resourceGroups {
		resourceTypes = append(resourceTypes, resourceType)
	}
	sort.Strings(resourceTypes)

	// Count total resources to know when we're at the last one
	totalResources := 0
	for _, resources := range resourceGroups {
		totalResources += len(resources)
	}
	currentResource := 0

	for _, resourceType := range resourceTypes {
		resources := resourceGroups[resourceType]
		for i, resource := range resources {
			currentResource++
			// Use sanitized name for consistency with OpenTofu configuration
			resourceName := g.sanitizeResourceName(resource.GetName())
			if i > 0 {
				resourceName = fmt.Sprintf("%s_%d", resourceName, i)
			}
			isLastResource := currentResource == totalResources
			content += g.generateStateResource(resource, resourceName, resourceType, isLastResource)
		}
	}

	content += `  ]
}
`

	return g.writeFile(filepath.Join(g.outputDir, "terraform.tfstate"), content)
}

// mapServiceToResourceType maps service types to specific OpenTofu resource types
func (g *Generator) mapServiceToResourceType(serviceType string) string {
	// Map service types to specific OpenTofu resource types
	resourceTypeMap := map[string]string{
		"vpc":           "vpc",
		"ec2":           "instance", // Most common EC2 resource
		"iam":           "iam_role", // Most common IAM resource
		"s3":            "s3_bucket",
		"route53":       "route53_zone",
		"rds":           "db_instance",
		"alb":           "lb",
		"elb":           "lb",
		"asg":           "autoscaling_group",
		"lambda":        "lambda_function",
		"sqs":           "sqs_queue",
		"sns":           "sns_topic",
		"cloudwatch":    "cloudwatch_log_group",
		"cloudtrail":    "cloudtrail",
		"config":        "config_configuration_recorder",
		"ecs":           "ecs_service",
		"eks":           "eks_cluster",
		"ecr":           "ecr_repository",
		"elasticache":   "elasticache_cluster",
		"redshift":      "redshift_cluster",
		"dynamodb":      "dynamodb_table",
		"elasticsearch": "elasticsearch_domain",
		"neptune":       "neptune_cluster",
		"docdb":         "docdb_cluster",
		"cloudfront":    "cloudfront_distribution",
		"apigateway":    "api_gateway_rest_api",
		"codebuild":     "codebuild_project",
		"codedeploy":    "codedeploy_app",
		"codecommit":    "codecommit_repository",
		"codepipeline":  "codepipeline",
		"elasticbeanstalk": "elastic_beanstalk_application",
		"ssm":           "ssm_parameter",
		"secretsmanager": "secretsmanager_secret",
		"kms":           "kms_key",
		"guardduty":     "guardduty_detector",
		"fsx":           "fsx_windows_file_system",
		"backup":        "backup_vault",
		"glacier":       "glacier_vault",
		"storagegateway": "storagegateway_gateway",
		"transfer":      "transfer_server",
		"kinesis":       "kinesis_stream",
		"firehose":      "kinesis_firehose_delivery_stream",
		"glue":          "glue_catalog_database",
		"athena":        "athena_database",
		"quicksight":    "quicksight_user",
		"mediastore":    "mediastore_container",
		"mediaconvert":  "media_convert_queue",
		"medialive":     "medialive_channel",
		"mediatailor":   "mediatailor_playback_configuration",
		"iot":           "iot_thing",
		"iotanalytics":  "iotanalytics_dataset",
		"iotevents":     "iotevents_detector_model",
		"iotsitewise":   "iotsitewise_asset_model",
		"iotthingsgraph": "iotthingsgraph_flow_template",
		"iotwireless":   "iotwireless_service_profile",
		"workspaces":    "workspaces_workspace",
		"mq":            "mq_broker",
	}

	if resourceType, exists := resourceTypeMap[serviceType]; exists {
		return resourceType
	}
	
	// Fallback to service type if no mapping exists
	return serviceType
}

// generateStateResource generates a state file resource entry
func (g *Generator) generateStateResource(resource aws.Resource, resourceName, resourceType string, isLastResource bool) string {
	// Map service type to specific OpenTofu resource type
	openTofuResourceType := g.mapServiceToResourceType(resourceType)
	
	// Generate a more complete state resource like Terraformer
	comma := ","
	if isLastResource {
		comma = ""
	}
	
	// For SNS topics, use the actual ARN as the ID
	// For other resources, use the actual AWS resource ID
	var resourceID string
	if resourceType == "sns" {
		// For SNS topics, the ID should be the actual ARN
		if snsResource, ok := resource.(*aws.SNSResource); ok {
			resourceID = snsResource.ARN
		} else {
			resourceID = resource.GetID()
		}
	} else {
		// For other resources, use the actual AWS resource ID
		resourceID = resource.GetID()
	}
	
	return fmt.Sprintf(`    {
      "mode": "managed",
      "type": "aws_%s",
      "name": "%s",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "%s",
            "arn": "%s",
            "name": "%s",
            "tags": %s,
            "tags_all": %s
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    }%s`, openTofuResourceType, resourceName, resourceID, resource.GetARN(), resource.GetName(), resource.GetTagsJSON(), resource.GetTagsJSON(), comma)
}

// formatTags formats tags for JSON output
func (g *Generator) formatTags(tags map[string]string) string {
	if len(tags) == 0 {
		return "{}"
	}

	tagPairs := make([]string, 0, len(tags))
	for k, v := range tags {
		tagPairs = append(tagPairs, fmt.Sprintf(`"%s": "%s"`, k, v))
	}
	sort.Strings(tagPairs)
	
	return fmt.Sprintf(`{%s}`, strings.Join(tagPairs, ", "))
} 